name: fark
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0
  simple_animations: ^1.1.3
  rxdart: ^0.24.1
  dropdownfield: ^1.0.3
  http: 
  image_picker: ^0.6.7+4
  mime_type: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/onboarding/
    - assets/image/icon/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/font/Product_Sans_Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
